version: '2.1'

services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    command: npm run build:prod && npm run serve

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  db:
    extends:
      file: docker-compose.yml
      service: db

volumes:
  node_modules:
  db: