version: '2.1'

services:
  web:
    extends:
      file: docker-common.yml
      service: web
    command: npm run build:prod && npm run serve
    volumes:
      - .:/usr/web/home/app
      - node_modules:/usr/web/home/app/node_modules
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8000", "||", "exit", "1"]
      timeout: 20s
      retries: 5
    depends_on:
      - redis
      - db

  redis:
    extends:
      file: docker-common.yml
      service: redis
    ports:
      - 6379:6379

  db:
    extends:
      file: docker-common.yml
      service: db
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: default_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: koa2_redux_universal
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  node_modules:
  db: