version: '2.1'

services:
  web:
    image: node:7.6.0-alpine
    build:
      context: .
      args:
        PORT: 8000
    volumes:
      - .:/usr/web/home/app
      - node_modules:/usr/web/home/app/node_modules
    ports:
      - 8000:8000

  redis:
    image: redis:3.2.9-alpine
    ports:
      - 6379:6379

  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: default_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: koa2_redux_universal
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  node_modules:
  db: