version: '2.1'

services:
  web:
    image: node:7.6.0-alpine
    build:
      context: .
      args:
        PORT: 8000
    volumes:
      - .:/usr/www/app
      - node_modules:/usr/www/app/node_modules
    ports:
      - 8000:8000

  redis:
    image: redis:3.2.9-alpine
    ports:
      - 6379:6379

volumes:
  node_modules: