version: '2.1'

services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    command: npm run build:prod && npm run serve:docker

  redis:
    extends:
      file: docker-compose.yml
      service: redis

volumes:
  node_modules: