const items = [{
  _id: '589b2bc5b399a2dae2a66af7',
  index: 0,
  guid: 'ffab5067-c4bd-4629-ba28-44b67a640175',
  isActive: false,
  balance: '$2,795.89',
  picture: 'http://placehold.it/32x32',
  age: 21,
  eyeColor: 'brown',
  name: 'Maryanne Byers',
  gender: 'female',
  company: 'MINGA',
  email: 'maryannebyers@minga.com',
  phone: '+1 (885) 556-3507',
  address: '789 Seagate Terrace, Mathews, Marshall Islands, 8689',
  about: 'Consequat labore laboris qui in ad laborum minim. Nostrud proident esse est id. Ullamco occaecat laborum excepteur non dolore. Et adipisicing aliqua quis dolore elit laborum.\r\n',
  registered: '2015-04-27T07:54:20 -08:00',
  latitude: 23.819716,
  longitude: 157.264684,
  tags: [
    'culpa',
    'ullamco',
    'Lorem',
    'eu',
    'deserunt',
    'ex',
    'culpa',
  ],
  friends: [
    {
      id: 0,
      name: 'Mckinney Wyatt',
    },
    {
      id: 1,
      name: 'Hurley Marsh',
    },
    {
      id: 2,
      name: 'Kline Kinney',
    },
  ],
  greeting: 'Hello, Maryanne Byers! You have 1 unread messages.',
  favoriteFruit: 'apple',
},
{
  _id: '589b2bc5f305255231cef020',
  index: 1,
  guid: '87cffb96-2d00-4955-9549-1cb8da13c6d4',
  isActive: false,
  balance: '$2,455.55',
  picture: 'http://placehold.it/32x32',
  age: 32,
  eyeColor: 'brown',
  name: 'Therese Carroll',
  gender: 'female',
  company: 'DEMINIMUM',
  email: 'theresecarroll@deminimum.com',
  phone: '+1 (937) 451-3138',
  address: '290 Berkeley Place, Eureka, Oklahoma, 2749',
  about: 'Ut mollit sit nostrud ullamco nisi elit nostrud reprehenderit nostrud officia ad. Ut eu mollit nisi minim. Ad culpa minim irure culpa. Adipisicing magna aliqua sunt tempor ut labore enim nostrud proident.\r\n',
  registered: '2015-01-13T03:40:49 -08:00',
  latitude: -53.829692,
  longitude: -146.414658,
  tags: [
    'eiusmod',
    'aute',
    'nulla',
    'nulla',
    'eu',
    'dolore',
    'consectetur',
  ],
  friends: [
    {
      id: 0,
      name: 'Carmela Delacruz',
    },
    {
      id: 1,
      name: 'Esther Henry',
    },
    {
      id: 2,
      name: 'May Conner',
    },
  ],
  greeting: 'Hello, Therese Carroll! You have 6 unread messages.',
  favoriteFruit: 'strawberry',
},
{
  _id: '589b2bc50b45192de34c3611',
  index: 2,
  guid: '0c895855-c63a-4021-8140-397c606a3a8e',
  isActive: false,
  balance: '$1,665.91',
  picture: 'http://placehold.it/32x32',
  age: 40,
  eyeColor: 'green',
  name: 'Boyer Tucker',
  gender: 'male',
  company: 'ERSUM',
  email: 'boyertucker@ersum.com',
  phone: '+1 (805) 447-3008',
  address: '300 Bryant Street, Cliff, Washington, 7249',
  about: 'Labore ad duis sint commodo anim qui labore cupidatat magna dolore deserunt duis pariatur ea. Dolor aliquip excepteur proident consequat id cillum anim. Pariatur magna anim irure officia do et. Consequat fugiat ex qui cupidatat sunt ut. Eu ut excepteur elit dolore officia labore eu incididunt irure nisi veniam esse anim velit. Do duis ex dolore dolor fugiat aliqua aliqua magna fugiat anim magna proident nulla. Duis commodo nisi aute do esse anim consectetur.\r\n',
  registered: '2014-01-11T08:59:57 -08:00',
  latitude: 74.317638,
  longitude: -72.496253,
  tags: [
    'adipisicing',
    'cupidatat',
    'ad',
    'sunt',
    'ut',
    'nisi',
    'proident',
  ],
  friends: [
    {
      id: 0,
      name: 'Dee Rivera',
    },
    {
      id: 1,
      name: 'Melva Carney',
    },
    {
      id: 2,
      name: 'Jannie Patterson',
    },
  ],
  greeting: 'Hello, Boyer Tucker! You have 8 unread messages.',
  favoriteFruit: 'apple',
},
{
  _id: '589b2bc5eab4fb6091c3ca30',
  index: 3,
  guid: 'ede8830d-b97c-4841-835e-5c81c3984e6d',
  isActive: false,
  balance: '$1,674.22',
  picture: 'http://placehold.it/32x32',
  age: 30,
  eyeColor: 'blue',
  name: 'Bass Charles',
  gender: 'male',
  company: 'STRALOY',
  email: 'basscharles@straloy.com',
  phone: '+1 (908) 400-3985',
  address: '591 Provost Street, Woodlake, Colorado, 7807',
  about: 'Tempor dolor commodo aliquip exercitation. Excepteur commodo magna fugiat amet quis commodo. Anim ipsum dolor voluptate eu consequat. Voluptate amet voluptate exercitation tempor pariatur cillum nisi proident voluptate labore tempor in. Excepteur consequat cupidatat laborum anim non fugiat consectetur elit ipsum est.\r\n',
  registered: '2015-04-16T02:44:55 -08:00',
  latitude: 42.488105,
  longitude: -123.468833,
  tags: [
    'nisi',
    'aliqua',
    'tempor',
    'qui',
    'labore',
    'incididunt',
    'proident',
  ],
  friends: [
    {
      id: 0,
      name: 'Julianne Douglas',
    },
    {
      id: 1,
      name: 'Joyce Marquez',
    },
    {
      id: 2,
      name: 'Alford Mosley',
    },
  ],
  greeting: 'Hello, Bass Charles! You have 4 unread messages.',
  favoriteFruit: 'apple',
},
{
  _id: '589b2bc5bdd7c2b96c47bbd9',
  index: 4,
  guid: '1af3a7b9-8e84-4498-9934-818fc90cb86a',
  isActive: false,
  balance: '$1,669.92',
  picture: 'http://placehold.it/32x32',
  age: 31,
  eyeColor: 'green',
  name: 'Sondra Mcintyre',
  gender: 'female',
  company: 'DIGINETIC',
  email: 'sondramcintyre@diginetic.com',
  phone: '+1 (958) 471-3700',
  address: '142 Post Court, Crayne, Pennsylvania, 7468',
  about: 'Minim consectetur in commodo dolor eiusmod Lorem non eu reprehenderit et proident officia. Dolor consequat pariatur dolor enim anim sit nostrud. Cillum esse eiusmod officia commodo commodo officia aliquip sit laborum velit sunt ex eu. Nulla aute ut amet excepteur consectetur veniam ipsum mollit. Aliquip esse ullamco qui velit Lorem non elit do excepteur excepteur. Nisi enim veniam qui ut consectetur do cupidatat magna culpa mollit. Lorem cupidatat exercitation est ea nulla nisi ipsum sint fugiat aliqua.\r\n',
  registered: '2016-02-09T03:08:50 -08:00',
  latitude: -84.007466,
  longitude: -104.13459,
  tags: [
    'velit',
    'sint',
    'reprehenderit',
    'aliquip',
    'commodo',
    'irure',
    'ullamco',
  ],
  friends: [
    {
      id: 0,
      name: 'Marissa Atkinson',
    },
    {
      id: 1,
      name: 'Marisol Lindsay',
    },
    {
      id: 2,
      name: 'Ingrid Blake',
    },
  ],
  greeting: 'Hello, Sondra Mcintyre! You have 5 unread messages.',
  favoriteFruit: 'strawberry',
},
{
  _id: '589b2bc531abb9ddc76568f3',
  index: 5,
  guid: '369389f5-5ff5-48f1-ba05-6cf368b27ae4',
  isActive: true,
  balance: '$2,404.78',
  picture: 'http://placehold.it/32x32',
  age: 30,
  eyeColor: 'green',
  name: 'Annabelle Cantu',
  gender: 'female',
  company: 'CINCYR',
  email: 'annabellecantu@cincyr.com',
  phone: '+1 (805) 455-2790',
  address: '463 Hewes Street, Washington, Minnesota, 658',
  about: 'Ex elit ullamco reprehenderit deserunt dolore irure sint proident ea. Culpa labore aute do ad labore reprehenderit tempor enim dolor sint dolor ea. Ea fugiat ad ut eiusmod consectetur eu sunt. Duis aute ullamco quis sit proident. Veniam consectetur ea exercitation in cillum. Elit sit nulla duis fugiat deserunt.\r\n',
  registered: '2016-11-05T09:35:05 -08:00',
  latitude: 6.321373,
  longitude: -114.993103,
  tags: [
    'officia',
    'sint',
    'et',
    'consequat',
    'magna',
    'minim',
    'dolor',
  ],
  friends: [
    {
      id: 0,
      name: 'Jacquelyn Cooper',
    },
    {
      id: 1,
      name: 'Mabel Rowe',
    },
    {
      id: 2,
      name: 'Daisy Matthews',
    },
  ],
  greeting: 'Hello, Annabelle Cantu! You have 10 unread messages.',
  favoriteFruit: 'apple',
}];

export default items;
